[project]
name = "giggity"
version = "0.1.0"
description = "Giggity Tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dulwich>=0.22.8",
    "jsonschema>=4.23.0",
    "pillow>=11.2.1",
    "urllib3>=2.4.0",
]

[tool.uv.workspace]
members = [
    "tools",
]
